-- Drop table

-- DROP TABLE public.product;

CREATE TABLE public.product (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	image varchar(255) NULL,
	name varchar(255) NULL,
	price numeric(19,2) NULL,
	score int2 NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id)
);